# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/80ccbfce-24fd-4b64-a47a-3b36bd1c28a4";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-7b02d0d6-c72f-4a56-bdd8-b30ac273d1b2".device =
    "/dev/disk/by-uuid/7b02d0d6-c72f-4a56-bdd8-b30ac273d1b2";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/825B-75F7";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/dde61b26-7179-45fc-82fa-0072d4747d36"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
