#!/usr/bin/env bash

sessions=$(tmux list-sessions -F "#{session_name}")
if [[ $# -eq 1 ]]; then
    selected=$1
else
    argss=$(fd -t d . / ~ /practice --max-depth 3 2> /dev/null)
    argss="$argss $sessions"
    selected=$(echo $argss | tr ' ' '\n'  | fzf --cycle)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
